### ISSUE TITLE
Thoughts on using yarn?

### ISSUE THREAD

**Issue by oshalygin** [GabiGrin/vscode-auto-run-command#1]
I'm going to add a bit of functionality because I want to use this utility in conjunction with an IIS express runner.  I don't work much on windows based applications but this would very handy for a maintenance project I have.

In conjunction with this:
https://marketplace.visualstudio.com/items?itemName=warren-buckley.iis-express

Anyways, I'd love to contribute but I wanted to get your input on using yarn before I submit a PR. Note, I intend to have other commits, not just slapping on a package manager.

Cheers and great work so far!

**Comment by GabiGrin** [comment]
I totally open for it as long as it keeps working. If you feel that it can be better, I'd be happy to add it.

**Comment by oshalygin** [comment]
It'll still work with `npm install` or any other means but this allows users to utilize yarn when resolving packages.  In addition to that, it's much more secure.  

No changes if you still want to use npm, just an added feature.
