### ISSUE TITLE
Condition request: hasExtension

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [GabiGrin/vscode-auto-run-command#18]
Using Wallaby.js as an example, it would be nice to run scripts if the user has the Wallaby extension _and_ a wallaby.js file exists.

**Comment by GabiGrin** [comment]
Hey @JoshuaKGoldberg,
That's a great idea. I'm not sure if vscode has an API for that, but if you find one and wanna try giving it a shot with a PR it'll be great!

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues in repos that haven't had updates in a few years. Cheers!
