### ISSUE TITLE
Thank-you note

### ISSUE THREAD

**Issue by Shawnuke** [GabiGrin/vscode-auto-run-command#37]
Hello,
I heard about Auto Run Command earlier today on stackoverflow.
It's not a strong use of your extension, but truth is: I was getting tired to have to re-open the integrated terminal window every time I open the application!
I didn't find a built-in way to di it, so I wanted to stop by and say "thank you"

Cheers

**Comment by GabiGrin** [comment]
Hey @Shawnuke!
Deep apologies for missing it, this message was a very nice surprise.
Thank you for that :)
