### ISSUE TITLE
Delay value as an option

### ISSUE THREAD

**Issue by xaduha** [GabiGrin/vscode-auto-run-command#41]
Hi, I'm using this extension to open/focus a new terminal and it works pretty well, with 0 seconds delay that is. Hardcoded 5 second delay seems unreasonable to me, at least it should be an option in the settings, no?

```` json
{
"auto-run-command.rules": [
        {
            "command": "workbench.action.terminal.focus",
        },
    ],
}
````

(haven't found a better way to open terminal window automatically)

**Comment by baincd** [comment]
Configuring the delay would be nice.  It could default to 5 to keep the current configuration by default.
