### ISSUE TITLE
Disable Auto run info on file open

### ISSUE THREAD

**Issue by dylanparry** [GabiGrin/vscode-auto-run-command#9]
Hi,

I was wondering if there is a way of disabling the info message that appears every time I open a project that doesn't have anything set to auto run on opening? That is, can I disable the message shown in the screenshot below:

![image](https://cloud.githubusercontent.com/assets/3692873/22693765/8b97d9e6-ed3c-11e6-968b-9915db72a926.png)

I have a fair few projects where I'm using Wallaby.js, and they are set to run it on startup, but most of my other projects (especially legacy ones) don't have or need to run anything, so I get this annoying message every time I open them.

Thanks,

Dylan

**Comment by GabiGrin** [comment]
Hey @dylanparry 
This is just just the placeholder command. To remove just go to your settings.json file and add an empty rule set:
```
	"auto-run-command.rules": [],
```

**Comment by dylanparry** [comment]
Exactly what I was looking for, thanks 👍
